package org.bukkit;

public enum Sound {
    UI_BUTTON_CLICK,
    BLOCK_NOTE_BLOCK_BELL,
    BLOCK_ANVIL_PLACE,
    ENTITY_PLAYER_LEVELUP,
    ENTITY_VILLAGER_NO,
    BLOCK_NOTE_BLOCK_PLING,
    ENTITY_EXPERIENCE_ORB_PICKUP,
    BLOCK_CHEST_OPEN
}
